# Example Database Configuration
# ------------------------------
# Supabase PostgreSQL Connection
# Values are loaded from the .env file
# ------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Avoid server-side prepared statement collisions with the pooler
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# ------------------------------
# JPA / Hibernate Configuration
# ------------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' automatically creates/updates tables based on your Entities during development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT Configuration
#app.jwtSecret=${JWT_SECRET}
app.jwtSecret=44c29697ae0528b8a9cbf43dc42cf5939b7d09a94af4942d6f5472dbe599f9dbcacb96269ae9a40e5a1589ea6505813cb8fb6fcfcc8ba6f71e0f1aa5e1e127d
#use .env for production
app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Cashfree Sandbox Credentials
cashfree.app.id=${CASHFREE_APP_ID}
cashfree.secret.key=${CASHFREE_SECRET_KEY}
cashfree.environment=${CASHFREE_ENVIRONMENT:SANDBOX}
# Your ngrok URL for local testing (Update this every time you restart ngrok)
cashfree.webhook.url=https://miasmal-francesco-lavishly.ngrok-free.dev/api/cashfree/webhook
